name: Go
on:
  pull_request:
    branches:
    - '**'
  push:
    branches:
    - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598
    - name: Write secret to a file
      run: echo "${{ secrets.blah }}" > test
    - name: Diff
      run: diff -wu README test
    strategy:
      matrix:
        os:
        - ubuntu-latest
        go_version:
        - go1.14.2
      fail-fast: false
